//========================================================================================
// (C) (or copyright) 2023. Triad National Security, LLC. All rights reserved.
//
// This program was produced under U.S. Government contract 89233218CNA000001 for Los
// Alamos National Laboratory (LANL), which is operated by Triad National Security, LLC
// for the U.S. Department of Energy/National Nuclear Security Administration. All rights
// in the program are reserved by Triad National Security, LLC, and the U.S. Department
// of Energy/National Nuclear Security Administration. The Government is granted for
// itself and others acting on its behalf a nonexclusive, paid-up, irrevocable worldwide
// license in this material to reproduce, prepare derivative works, distribute copies to
// the public, perform publicly and display publicly, and to permit others to do so.
//========================================================================================
#ifndef RADIATION_DIFFUSION_MULTIGROUP_DIFFUSION_HPP_
#define RADIATION_DIFFUSION_MULTIGROUP_DIFFUSION_HPP_

#include <parthenon/driver.hpp>
#include <parthenon/package.hpp>
#include <solvers/bicgstab_solver.hpp>
#include <solvers/solver_base.hpp>
#include <tasks/task_timing.hpp>
#include <utils/constants.hpp>

// RiotLimits::MAX_GROUPS (the compile-time upper bound on the number of energy groups)
// is defined here. This header is generated by CMake from src/riot_limits.hpp.in so the
// limit can be set at configure time (RIOT_MAX_GROUPS).
#include <riot_limits.hpp>

using namespace parthenon::package::prelude;
using namespace parthenon::driver::prelude;

namespace RadiationDiffusion {

using RiotLimits::MAX_GROUPS;

template <class temperature>
struct MultiGroup {
  // Stage names for interfacing with solvers
  inline static const std::string multigroup_base_container = "multigroup_base";
  inline static const std::string multigroup_u_container = "multigroup_u";
  inline static const std::string multigroup_rhs_container = "multigroup_rhs";

  // Routines in multigroup_diffusion-package.cpp
  static std::shared_ptr<StateDescriptor> Initialize(ParameterInput *pin,
                                                     StateDescriptor *materials);

  static TaskCollection Step(Mesh *pm, parthenon::SimTime &tm, const Real dt);

  static AmrTag CheckRefinement(MeshBlockData<Real> *rc);

  static Real EstimateTimestepMesh(MeshData<Real> *md);

  static void MeshPostProblemGenerator(parthenon::Mesh *mesh,
                                       parthenon::ParameterInput *pin,
                                       parthenon::MeshData<Real> *md);
};

// Routines in mutigroup_diffusion-solvers.cpp
template <class temperature>
std::shared_ptr<parthenon::solvers::SolverBase> GetSolverSptr(ParameterInput *pin);

template <class temperature>
struct MultiGroupTasks {
  // Routines in multigroup_diffusion-tasks.cpp
  static parthenon::TaskStatus Completion(std::shared_ptr<AllReduce<Real>> step_norm,
                                          Mesh *pmesh, int partition);

  static parthenon::TaskStatus
  SaveStarState(std::shared_ptr<parthenon::MeshData<Real>> md,
                std::shared_ptr<parthenon::MeshData<Real>> md_star);

  static parthenon::TaskStatus
  InitializeRadiationQuantities(std::shared_ptr<parthenon::MeshData<Real>> md_base,
                                std::shared_ptr<parthenon::MeshData<Real>> md_star,
                                std::shared_ptr<parthenon::MeshData<Real>> md_matrix,
                                std::shared_ptr<parthenon::MeshData<Real>> md_rhs,
                                Real dt);
  static parthenon::TaskStatus
  ApplyUpdate(std::shared_ptr<parthenon::MeshData<Real>> md_star,
              std::shared_ptr<parthenon::MeshData<Real>> md_u,
              std::shared_ptr<parthenon::MeshData<Real>> md_base);
  static parthenon::TaskStatus
  LocalSolve(std::shared_ptr<parthenon::MeshData<Real>> md_star,
             std::shared_ptr<parthenon::MeshData<Real>> md_base, Real dt, int niter);

  static parthenon::TaskStatus
  CorrectTotalEnergy(std::shared_ptr<parthenon::MeshData<Real>> md_base);

  static parthenon::TaskStatus
  SetLaggedRadiationMomentumFlux(std::shared_ptr<parthenon::MeshData<Real>> md_star,
                                 std::shared_ptr<parthenon::MeshData<Real>> md_base,
                                 Real dt);

  static parthenon::TaskStatus
  UpdateRadiationMomentum(std::shared_ptr<parthenon::MeshData<Real>> md_star,
                          std::shared_ptr<parthenon::MeshData<Real>> md_base, Real dt);

  static parthenon::TaskStatus
  InitializeGeometry(std::shared_ptr<parthenon::MeshData<Real>> &md_mat);
};
} // namespace RadiationDiffusion

#endif // RADIATION_DIFFUSION_MULTIGROUP_DIFFUSION_HPP_
