//========================================================================================
// (C) (or copyright) 2023-2026. Triad National Security, LLC. All rights reserved.
//
// This program was produced under U.S. Government contract 89233218CNA000001 for Los
// Alamos National Laboratory (LANL), which is operated by Triad National Security, LLC
// for the U.S. Department of Energy/National Nuclear Security Administration. All rights
// in the program are reserved by Triad National Security, LLC, and the U.S. Department
// of Energy/National Nuclear Security Administration. The Government is granted for
// itself and others acting on its behalf a nonexclusive, paid-up, irrevocable worldwide
// license in this material to reproduce, prepare derivative works, distribute copies to
// the public, perform publicly and display publicly, and to permit others to do so.
//========================================================================================
#ifndef MATERIALS_MATERIALS_HPP_
#define MATERIALS_MATERIALS_HPP_
// This file was made in part with generative AI.

#include <kokkos_abstraction.hpp>
#include <memory>
#include <parthenon/package.hpp>

// RiotLimits::MAX_MATERIALS, MAX_STRONG, MAX_ADV, and MAX_GROUPS are defined here. This
// header is generated by CMake from src/riot_limits.hpp.in so the limits can be set at
// configure time.
#include <riot_limits.hpp>

using namespace parthenon::package::prelude;

namespace Materials {

std::shared_ptr<StateDescriptor> Initialize(ParameterInput *pin);
void PostInitialization(Mesh *pm, ParameterInput *pin, MeshData<Real> *md);

#ifdef SPINER_USE_HDF
// Read isotope masses/charges for the requested zaids from an HDF5 isotope-data file.
// Defined in materials.cpp; declared here so Initialize can precede it in the .cpp.
void read_isotope_data_from_hdf5(const std::string &filename,
                                 const std::vector<int> &requested_zaids,
                                 std::vector<Real> &masses, std::vector<int> &charges);
#endif

template <typename... Args>
void AddMatId(int matid, std::vector<int> shape, SparsePool &p, Args &&...args) {
  p.Add(matid, shape);
  if constexpr (sizeof...(Args) > 0) AddMatId(matid, shape, std::forward<Args>(args)...);
}

template <typename... Args>
void AddPools(StateDescriptor *s, SparsePool &p, Args &&...args) {
  s->AddSparsePool(p);
  if constexpr (sizeof...(Args) > 0) AddPools(s, std::forward<Args>(args)...);
}

int CountMaterials(ParameterInput *pin);
} // namespace Materials

#endif // MATERIALS_MATERIALS_HPP_
